
<div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-2 main" >
    <h1 class="page-header" style="border-bottom: 2px solid #428BCA;">Historia de la UNSAM</h1>
    <img src="http://www.unsam.edu.ar/img/top_historia.jpg" width="600" height="172" alt="imagen del campus" />
    
    <p>Radicada en la ciudad de la tradici&oacute;n y  capital de la industria, la UNSAM fue creada como respuesta a dos necesidades:  la descentralizaci&oacute;n de las grandes universidades y el deseo de la comunidad de  San Mart&iacute;n de contar con una universidad en su territorio. <br />
        La  iniciativa tuvo origen en la Biblioteca Popular de San Mart&iacute;n, impulsada por un  grupo de vecinos. En julio de 1990 el diputado Antonio Libonatti present&oacute; ante  la C&aacute;mara de Diputados el Proyecto de Ley de Creaci&oacute;n de la Universidad  Nacional de San Mart&iacute;n. Esa iniciativa condujo a la fundaci&oacute;n de la UNSAM, el  10 de junio de 1992, por Ley de la Naci&oacute;n No. 24.095.&nbsp; <br />
        El Poder  Ejecutivo design&oacute; a Daniel Malcolm como Rector organizador. Las primeras  actividades acad&eacute;micas de grado y posgrado tuvieron lugar en 1994.<br />
        En abril de ese a&ntilde;o, en un sector  del Patio Esqui&uacute; del Liceo Militar, se dio inicio a los cursos que derivar&iacute;an  en la primera promoci&oacute;n de alumnos de la Escuela de Econom&iacute;a y Negocios, la  &ldquo;Promoci&oacute;n 1994&rdquo;.</p>
    <p><h2>Algunos hitos</h2></p>
<p><strong>1995</strong>. Se crean el  Instituto Sabato (en asociaci&oacute;n con la Comisi&oacute;n Nacional de Energ&iacute;a At&oacute;mica) y  el Instituto de la Calidad Industrial (en asociaci&oacute;n con el Instituto Nacional  de Tecnolog&iacute;a Industrial).</p>
<p><strong>1996</strong>. Se crean el  Instituto de Investigaciones Biotecnol&oacute;gicas (IIB) y el Programa de Pol&iacute;tica y  Gobierno. </p>
<p><strong>1997</strong>. Daniel Malcolm es electo rector y Agust&iacute;n Pieroni,  vicerrector. En julio se firma el convenio de colaboraci&oacute;n que  formaliza la creaci&oacute;n del Polo Tecnol&oacute;gico Constituyentes (PTC), junto a la  Comisi&oacute;n Nacional de Energ&iacute;a At&oacute;mica (CNEA), el Instituto Nacional de  Tecnolog&iacute;a Industrial (INTI), el entonces Centro de Investigaciones Cient&iacute;ficas  y T&eacute;cnicas de las Fuerzas Armadas (CITEFA, hoy CITEDEF) y el Servicio Geol&oacute;gico  Minero Argentino (SEGEMAR).</p>
<p><strong>1998</strong>. Se firma  un convenio con la Fundaci&oacute;n de Altos Estudios Sociales y se crea el Instituto  de Altos Estudios Sociales&nbsp; (IDAES), un  instituto de docencia de posgrado en ciencias sociales. El director es Jos&eacute;  Nun.</p>
<p><strong>1999</strong>. Se crea la Escuela de Humanidades y Carlos Ruta asume  como primer decano. Mediante la fusi&oacute;n del IIB-UNSAM y el Instituto Tecnol&oacute;gico  de Chascom&uacute;s (INTECH) del CONICET, se crea el IIB-INTECH, un instituto de  investigaci&oacute;n, desarrollo y docencia de grado y posgrado en el &aacute;rea  biotecnol&oacute;gica. Se crea el  Instituto de Ciencias de la Rehabilitaci&oacute;n y el Movimiento (ICRM). </p>
<p><strong>2000</strong>. La Escuela de  Pol&iacute;tica y Gobierno lanza la Maestr&iacute;a en Pol&iacute;ticas P&uacute;blicas y Gerenciamiento  del Desarrollo, creada a partir del acuerdo entre la Universidad de Georgetown  y la Universidad de San Mart&iacute;n. </p>
<p><strong>2001</strong>. El  INCALIN lanza la Especializaci&oacute;n de Calidad Industrial en Alimentos. Se  empieza a construir el Campus Miguelete, hoy sede central, en un predio de  cuatro hect&aacute;reas cedido por el Estado Nacional. A partir de entonces se inicia  un proceso de recuperaci&oacute;n de los edificios con valor hist&oacute;rico y  arquitect&oacute;nico. Ese Plan Maestro recibe el premio iberoamericano a la mejor  intervenci&oacute;n en el patrimonio edificado para obras de m&aacute;s de 1000 m2. Se crea  la Escuela de Pol&iacute;tica y Gobierno, siendo su primer decano Marcelo Cavarozzi.</p>
<p><strong>2002</strong>. Daniel Malcolm y Agust&iacute;n Pieroni son reelectos como  Rector y Vicerrector de la Universidad. Egresa la primera camada de la Escuela  de Econom&iacute;a y Negocios.</p>
<p><strong>2003</strong>. Comienza la puesta en valor del Edificio Corona del  Tornav&iacute;as, un gran c&iacute;rculo con apariencia de coliseo donde antes funcionaban  los talleres del ferrocarril, que hoy alberga aulas, laboratorios y &aacute;reas de  servicios centrales. </p>
<p><strong>2004</strong>. Se crea el Centro de Producci&oacute;n e  Investigaci&oacute;n en Restauraci&oacute;n y Conservaci&oacute;n Art&iacute;stica y Bibliogr&aacute;fica TAREA  (CEIRCAB TAREA), bajo la direcci&oacute;n de Jos&eacute; Emilio Buruc&uacute;a, y reabre el legendario  taller creado por la Fundaci&oacute;n Tarea, que hab&iacute;a cerrado en 1997. El 17 de  agosto se inaugura el edificio Corona del Tornav&iacute;a. </p>
<p><strong>2006</strong>. En febrero Daniel Malcolm es nombrado Secretario de  Pol&iacute;ticas Universitarias de la Naci&oacute;n; Carlos Ruta es electo Rector y Carlos  Gianella, vicerrector. El 24 de febrero el soci&oacute;logo franc&eacute;s Alain Touraine  visita la UNSAM y recibe el Doctorado Honoris Causa.&nbsp; Alberto Carlos Frasch, decano del IIB-INTECH,  es nombrado miembro extranjero de la <em>National  Academy of Sciences </em>de Estados Unidos por sus contribuciones al estudio del <em>Trypanosoma cruzi</em>-Enfermedad de  Chagas. <em>Iluminados por el fuego</em>,  dirigida por Trist&aacute;n Bauer con el apoyo de la UNSAM, gana el Goya a la mejor  producci&oacute;n extranjera de habla hispana. Se crea el Instituto de Tecnolog&iacute;a  Nuclear Dan Beninson (IDB) a trav&eacute;s de un convenio entre la Comisi&oacute;n Nacional  de Energ&iacute;a At&oacute;mica (CNEA) y la Universidad Nacional de General San Mart&iacute;n (UNSAM).</p>
<p><strong>2007</strong>. El  polit&oacute;logo Guillermo O'Donnell se incorpora a la UNSAM y se crea  el Centro de Investigaciones sobre el Estado y la Democracia en Am&eacute;rica Latina.  Se firma el convenio para la creaci&oacute;n del Instituto Tecnol&oacute;gico Ferroviario  Ra&uacute;l Scalabrini Ortiz. Se lanzan la Licenciatura en Ciencia Pol&iacute;tica y la  Licenciatura en Administraci&oacute;n P&uacute;blica. En diciembre, el vicerrector Gianella,  asume un cargo en la Comisi&oacute;n de Investigaciones Cient&iacute;ficas de la provincia de  Buenos Aires (CIC).  Alejandro Grimson es nombrado decano del IDAES.</p>
<p><strong>2008</strong>. Se funda el Laboratorio de Bioseguridad  Nivel 3, de 600 m2. Son seleccionados veintitr&eacute;s proyectos de Investigaci&oacute;n del  Programa PICT por la Agencia Nacional de Promoci&oacute;n de la Ciencia y la  Tecnolog&iacute;a. En julio empieza a  funcionar el Instituto de Investigaci&oacute;n e Ingenier&iacute;a Ambiental (3iA). El  Taller TAREA empieza la puesta en valor del mural <em>Ejercicio Pl&aacute;stico</em> del pintor mexicano David Alfaro Siqueiros. Se  publica la edici&oacute;n del <em>Crimen de la Guerra</em> de Juan Bautista  Alberdi a cargo de la doctora &Eacute;lida Lois, presentada por Horacio Gonz&aacute;lez, Eugenio  Zaffaroni, Natalio Botana y Carlos Ruta en la Biblioteca Nacional. </p>
<p><strong>2009</strong>.<strong> </strong>Joaqu&iacute;n Vald&eacute;s, decano del INCALIN, es nombrado miembro del Comit&eacute;  Internacional de Pesas y Medidas, una instituci&oacute;n creada en 1875 que armoniza  todo lo que se mide a nivel mundial. El IIB-INTECH inicia el programa de  clonaci&oacute;n y transg&eacute;nesis de grandes animales y se clona por primera vez un toro  de la raza Brangus. Mariano Ianuzzi, egresado del Instituto Sabato, recibe  el premio Morris Cohen de la<em> Electrochemical  Society</em>.</p>
<p><strong>2010</strong>. En febrero Ruta asume su segundo mandato y Daniel Di  Gregorio, hasta ese momento decano de la Escuela de Ciencia y Tecnolog&iacute;a, asume  como vicerrector. Se crea el Programa Lectura Mundi, que aloja a la  Biblioteca Central. Su primera acci&oacute;n  p&uacute;blica es la entrega la distinci&oacute;n <em>honoris  causa</em> al historiador Roger Chartier. En noviembre organiza la elecci&oacute;n del  libro del Bicentenario y la comunidad universitaria elige <em>Mart&iacute;n Fierro</em>. La presidenta Cristina Fern&aacute;ndez de Kirchner  inaugura el Mural Siqueiros, que luego de dos a&ntilde;os de reparaci&oacute;n es emplazado  nuevamente en la Aduana de Taylor, ubicada en Casa Rosada y parte del  Museo del Bicentenario. En  el ranking iberoamericano, la UNSAM figura primera a nivel nacional en calidad  de producci&oacute;n cient&iacute;fica. La pel&iacute;cula <em>Che, un  hombre nuevo</em>, realizada por el titular del Sistema Nacional de Medios  P&uacute;blicos, Trist&aacute;n Bauer, recibe el Premio al Mejor Film Documental, otorgado  por el voto del p&uacute;blico, en el festival de cine de Montreal.</p>
<p><strong>2011</strong>. El IIB-INTECH  clona el primer bovino transg&eacute;nico productor de leche humanizada, conocido como  la vaca ISA o Rosita. Se inaugura la  C&aacute;tedra Pierre Menard dirigida por Alberto Manguel, en el Programa Lectura  Mundi. La UNSAM participa de cinco proyectos del Programa de  Fondos Argentinos Sectoriales seleccionados por el Ministerio de Ciencia. El poeta y periodista Juan Gelman,  galardonado con el Premio Cervantes en 2007 y radicado en M&eacute;xico, participa de  un encuentro con el p&uacute;blico organizado por la UNSAM. Se inaugura la Carpa en el  Campus Miguelete. La escritora, psicoanalista y profesora  em&eacute;rita de la Universidad de Par&iacute;s VII Diderot Julia Kristeva visita la UNSAM y  dicta varias conferencias en el marco del convenio UNSAM-Paris VII.</p>
<p><strong>2012</strong>. La UNSAM inicia los festejos por  los 20 a&ntilde;os. Le entrega el doctor Honoris Causa a Alain Badiou, el fil&oacute;sofo  franc&eacute;s.</p>
<p><br />
    <br />
    <img src="http://www.unsam.edu.ar/img/historia.jpg" width="600" height="200" alt="foto del campus" />                                </p>
</p>

</div>